---
title: '2018-10-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50),
  stringsAsFactors = F
  )
StuDF
```

```{r}
library(stringr)
fruits <- c(
  "apples and oranges and pears and bananas",
  "pineapples and mangos and guavas"
)

str_split(fruits, " and ")
str_split(fruits, " and ", simplify = TRUE)

```

```{r}
names(StuDF) 
colnames(StuDF)
```


```{r}
rownames(StuDF)
```

```{r}
StuDF[1,2]
StuDF[,2]
StuDF[1,]
StuDF[c(1,4),]
StuDF[c(1,4),c(2,3)]
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
levels(student$身高級距)<-c("小個子","小個子","小個子","小個子","小個子","中等個子","中等個子","高個子","高個子")
levels(student$身高級距)
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
student$新身高級距 <- student$身高級距
levels(student$新身高級距)[1:3] <- c("(0,160]")
```
```{r}
library(googlesheets)
gs_auth(new_user = TRUE)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```

```{r}
dim(classSurvey)
```

```{r}
as.character(classSurvey$學號)
library(stringr)
classSurvey$年級 <- str_sub(classSurvey$學號,2,4)
# 年級 轉 factor
classSurvey$年級 <- as.factor(classSurvey$年級)
# 年級進行 generic replacement
levels(classSurvey$年級) <- c("大四及以上","大三","大二","大一")
```




```{r}
library(readr)
collegeData <- read_csv("https://quality.data.gov.tw/dq_download_csv.php?nid=6231&md5_url=dda8fca407131483c1d8cbf3d61cf793")
```


```{r}
as.factor(collegeData$學校名稱) ->collegeData$學校名稱
as.factor(collegeData$學校代碼) ->collegeData$學校代碼
collegeData -> collegeData2
```

```{r}
as.factor(collegeData$`日間∕進修別`)->collegeData$`日間∕進修別`
as.factor(collegeData$等級別)->collegeData$等級別
as.numeric(collegeData$一年級男生)->collegeData$一年級男生
as.numeric(collegeData$一年級女生)->collegeData$一年級女生

```
```{r}
library(stringr)
library(dplyr)
collegeData %>% 
  mutate(   # 將所有逗號拿掉
    一年級男生=str_replace(一年級男生,",",""),
    一年級女生=str_replace(一年級女生,",","")
  ) %>%
  mutate(
    `日間∕進修別`=as.factor(`日間∕進修別`),
    等級別=as.factor(等級別),
    一年級男生=as.numeric(一年級男生),
    一年級女生=as.numeric(一年級女生)
  ) -> collegeData3
```

```{r}
library(readr)
cl<-locale(grouping_mark = ",") # 創造cl來描述千分位符號使用","的習慣場景
collegeData %>% 
  mutate(
    `日間∕進修別`=as.factor(`日間∕進修別`),
    等級別=as.factor(等級別),
    一年級男生=parse_number(一年級男生,locale=cl, na = c("", "NA","-")),
    一年級女生=parse_number(一年級女生,na = c("", "NA","-"),locale=cl),
  ) -> collegeData4
```

```{r}
x <- c(0:10, 50)
xm <- mean(x)
c(xm, mean(x, trim = 0.10))
```

```{r}
str_c("Letter: ", letters)
```

