---
title: "2018-12-12"
output: html_document
---
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")

```



```{r}
library(stringr)
a<-c("A, B","B, C")
a
str_split_fixed(a,", ", n=3)->b
str_c(b)->c
c
table(b)
b
```
```{r}
library(googlesheets)
gs_auth(new_user = TRUE)
## ----ans22---------------------------------------------------------------
deadline3 <- ymd_hms("2018-11-06 00:00:00",tz="Asia/Taipei")
hwSubmit3 <- hwSubmit[hwSubmit$作業代碼=="Exercise3",]
hwSubmit3 %>%
  mutate(
    截止時差=difftime(deadline3,Timestamp,units="hours")
  ) -> 
  hwSubmit3
hwSubmit[hwSubmit$作業代碼 =="Exercise3",] -> hwSubmit3
hwSubmit3$Timestamp -> time
difftime("2018-11-06 00:00:00", time, units="hours") -> hwSubmit3$截止時差

```

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
library(dplyr)
library(lubridate)
libraryData %>%
  mutate(
    學院=as.factor(學院),
    書籍館藏地=as.factor(書籍館藏地),
    書籍類別=as.factor(書籍類別),
    借閱時間=ymd_hms(借閱時間,tz="Asia/Taipei")
  ) -> libraryData
```

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
library(dplyr)
libraryData$書籍館藏地 %>% as.factor %>% levels -> storageLocations
storageLocations
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
```

```{r}
for(i in c(1:18)){# 1
storageLocation_i <- storageLocations[i] 
# 2
numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
# 4
allBorrowCount[[i]] <-borrowCount_i}

allBorrowCount
```

```{r}
library(dplyr)
libraryData$學院 %>% as.factor %>% levels -> storageColleges
storageColleges
```

```{r}
CollegeBorrowCount <- vector("numeric",length(storageCollege)) #可把數字改成length()
for(i in c(1:length(storageCollege))){# 1
storageCollege_i <- storageColleges[i] 
# 2
numericalIndexForSubsample<-which(libraryData$學院==storageCollege_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
# 4
CollegeBorrowCount[[i]] <-borrowCount_i}

CollegeBorrowCount

```


```{r}
library(dplyr)
libraryData$學號 %>% as.factor %>% levels -> Students
##或者寫成libraryData$學號 %>% unique -> Students
Students
```

```{r}
StudentBorrowCount <- vector("numeric",length(Students)) #可把數字改成length()
for(i in c(1:length(Students))){# 1
Student_i <- Students[i] 
# 2
numericalIndexForSubsample<-which(libraryData$學號==Student_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
# 4
StudentBorrowCount[[i]] <-borrowCount_i}

max(StudentBorrowCount)
```

